"""Auto-install orchestrator for external dependency blockers.

Generates conftest_autofixes.py to automatically install missing/outdated
packages during pytest initialization.
"""

from pathlib import Path
from typing import List, Dict, Any, Optional
import logging

logger = logging.getLogger(__name__)


class AutoInstallOrchestrator:
    """Orchestrates automatic installation of blockers."""
    
    CONFTEST_PATH = ".ptsd/conftest_autofixes.py"
    
    def __init__(self, config: Dict[str, Any]):
        """Initialize orchestrator.
        
        Args:
            config: Configuration dictionary with auto_install settings
        """
        self.config = config
        self.auto_install_config = config.get('dependency_updates', {}).get('auto_install', {})
    
    def should_install(self, package: str, version: str = None) -> tuple[bool, str]:
        """Check if package meets safety requirements for installation.
        
        Args:
            package: Package name
            version: Optional version requirement
        
        Returns:
            Tuple of (should_install: bool, reason: str)
        """
        # Check whitelist
        allowed_packages = self.auto_install_config.get('allowed_packages', [])
        if allowed_packages and package not in allowed_packages:
            return False, f"Package not in whitelist: {package}"
        
        # TODO: Add package size check via PyPI API
        # For now, assume all packages are acceptable
        
        return True, "OK"
    
    def generate_conftest_autofixes(self, blockers: List[Dict[str, Any]]) -> Path:
        """Generate conftest_autofixes.py for pytest to auto-install packages.
        
        Args:
            blockers: List of external blocker dictionaries
        
        Returns:
            Path to generated conftest file
        """
        if not blockers:
            logger.debug("No blockers to install")
            return None
        
        # Filter blockers by safety check
        installable = []
        for blocker in blockers:
            package = blocker.get('package')
            version = blocker.get('required_version')
            
            should_install, reason = self.should_install(package, version)
            if should_install:
                installable.append(blocker)
            else:
                logger.warning(f"Skipping {package}: {reason}")
        
        if not installable:
            logger.info("No installable blockers after safety check")
            return None
        
        # Generate conftest code
        conftest_code = self._generate_conftest_code(installable)
        
        # Write to file
        conftest_path = Path(self.CONFTEST_PATH)
        conftest_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(conftest_path, 'w') as f:
            f.write(conftest_code)
        
        logger.info(f"Generated {conftest_path} with {len(installable)} auto-fixes")
        return conftest_path
    
    def _generate_conftest_code(self, blockers: List[Dict[str, Any]]) -> str:
        """Generate Python code for conftest_autofixes.py.
        
        Args:
            blockers: List of installable blockers
        
        Returns:
            Python code as string
        """
        timeout = self.auto_install_config.get('install_timeout', 300)
        
        # Build fixes list
        fixes_code = "    fixes = [\n"
        for blocker in blockers:
            pkg = blocker.get('package')
            cmd = blocker.get('install_command', f"pip install {pkg}")
            reason = blocker.get('reason', 'Dependency update required')
            components = blocker.get('blocking_components', [])
            comp_str = ', '.join([f"Phase {c['phase']}:{c['component']}" for c in components])
            
            fixes_code += f"""        {{
            'package': '{pkg}',
            'command': \"{cmd}\",
            'reason': '{reason}',
            'components': ['{comp_str}']
        }},\n"""
        fixes_code += "    ]\n"
        
        code = f'''"""Auto-generated by PTSD Agent - Auto-Install Blockers
This file is executed BEFORE your tests run to fix dependency blockers.
Generated: {{datetime.now().isoformat()}}
"""

import subprocess
import sys
from datetime import datetime

def install_blocker_fixes():
    """Install packages to fix external blockers from previous run."""
    
{fixes_code}
    
    print("=" * 60)
    print("PTSD Agent: Auto-Installing Blocker Fixes")
    print("=" * 60)
    
    for fix in fixes:
        print(f"\\n✓ Installing {{fix['package']}}")
        print(f"   Reason: {{fix['reason']}}")
        print(f"   Unblocks: {{', '.join(fix['components'])}}")
        
        try:
            result = subprocess.run(
                fix['command'],
                shell=True,
                capture_output=True,
                text=True,
                timeout={timeout}
            )
            
            if result.returncode == 0:
                print(f"   ✓ Installed successfully")
            else:
                print(f"   ✗ Installation failed:")
                print(f"   {{result.stderr}}")
                sys.exit(1)
                
        except subprocess.TimeoutExpired:
            print(f"   ✗ Installation timeout ({timeout}s)")
            sys.exit(1)
        except Exception as e:
            print(f"   ✗ Error: {{e}}")
            sys.exit(1)
    
    print("\\n" + "=" * 60)
    print("✓ All blockers resolved - tests can proceed")
    print("=" * 60 + "\\n")

# Execute on conftest load
install_blocker_fixes()
'''
        return code
    
    def cleanup_conftest(self):
        """Remove generated conftest file."""
        conftest_path = Path(self.CONFTEST_PATH)
        if conftest_path.exists():
            conftest_path.unlink()
            logger.debug(f"Removed {conftest_path}")
